name: Deploy to GitHub Pages

on:
  schedule:
    # 1時間ことに定期実行
    - cron: "0 * * * *"
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Python script
        run: python cli.py save-batch
        env:
          TLE_LIST: ${{ secrets.TLE_LIST }}

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        env:
          OUTPUT_DIR: "./docs"
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
