name: Deploy to GitHub Pages

on:
  schedule:
    # 1時間ことに定期実行
    - cron: "0 * * * *"
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Python script
        run: python cli.py save-batch
        env:
          TLE_LIST: ${{ secrets.TLE_LIST }}
          OUTPUT_DIR: ./docs

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          branch: gh-pages
          folder: ./docs
          clean: true
          commit-message: Deploy as of ${GITHUB_SHA}
